name: ci

on:
  push:
    branches:
      - ios-custom-build
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  ci:
    name: iOS universal video-default
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Platform info
        run: |
          printf "%-23s %s\n" "